### ISSUE TITLE
cache invalidation on multiple servers

### ISSUE THREAD

**Issue by laureysruben** [moozzyk/EFCache#10]
Hi,

We've been using efcache in our new projects, but bumped into a problem since we pushed to our live environment. In our live environment we've got 2 servers and a load balancer.
Now when the cache is invalidated (because of an update to the data), this only happens on one server. The other server keeps the old cache, and data is out of sync.

Is there any way to get 2 (or more) servers to invalidate the cache at once? In older projects we used a file dependency on a shared file server to invalidate cache, is there any way to do this with efcache?

Kind regards,

Ruben

**Comment by moozzyk** [comment]
The default implementation is using memory cache so each server caches results independently. You can plug in a different implementation (e.g. [Redis based](https://www.nuget.org/packages/EFCache.Redis/)) which will be shared by all the servers. In this scenario the cache is common to all the servers.
