### ISSUE TITLE
Error 152: The Entity Framework provider type 'EFCache.CachingProviderServices, EFCache, Version=1.1.0.0, Culture=neutral, PublicKeyToken=46c4868af4307d2c' did not have a static property or field named 'Instance'. Entity Framework providers must declare a static property or field named 'Instance' that returns the Singleton instance of the provider.

### ISSUE THREAD

**Issue by MagicAndre1981** [moozzyk/EFCache#11]
I've installed the EFCache package and now I get this error message:

`Error 152: The Entity Framework provider type 'EFCache.CachingProviderServices, EFCache, Version=1.1.0.0, Culture=neutral, PublicKeyToken=46c4868af4307d2c' did not have a static property or field named 'Instance'. Entity Framework providers must declare a static property or field named 'Instance' that returns the Singleton instance of the provider.`

![grafik](https://cloud.githubusercontent.com/assets/8274816/26387753/3e608da0-4050-11e7-8521-aba601790b08.png)

I'm using .net 4.5.2 with EF6.1.3 and [Firebird .net Provider 5.9.1](https://www.nuget.org/packages/FirebirdSql.Data.FirebirdClient/).

The application runs, but I have no idea if the cache is ever used.

**Comment by moozzyk** [comment]
Are you using Model/Database First or CodeFirst?

**Comment by MagicAndre1981** [comment]
I use DbContext API, but reverse engineer the DB into a EDMX, to have a better visual overview, rename data and later I use a t4 script to generate the Context and the classes

**Comment by moozzyk** [comment]
But do you use this edmx in any way? I believe the error is a design time error that happens because you have an edmx file open. The edmx file has a provider manifest token probably pointing to EFCache provider. Since VS can't find this provider it fails. I think that if you close the edmx file in VS the error will go away. As I pointed out, this is a I believe it is a design time and won't affect your application if you don't use this edmx.

**Comment by MagicAndre1981** [comment]
no, the EDMX is closed. I get this each time during compile.

**Comment by moozzyk** [comment]
Did you add the edmx to the project then?

**Comment by MagicAndre1981** [comment]
yes, the EDMX is part of the project, because there is no Fluent T4 script that supports EF6 (only EF5: https://marketplace.visualstudio.com/items?itemName=IFle.EF5xDbContextFluentGeneratorforC), I must use the EDMX at runtime for the mapping.

**Comment by moozzyk** [comment]
This is the problem. EF5 provider model was different from EF6. Can't help with your problem - it's outside EF Cache, sorry.

**Comment by MagicAndre1981** [comment]
I'M NOT USING EF5 provider!!!!!!!!!!!!! I used this in the past with EF5!!!!!!!! Is this so hard to understand!!!

**Comment by moozzyk** [comment]
Yes. You said your T4 script is using EF5.

**Comment by MagicAndre1981** [comment]
I never said this, learn to read.

**Comment by MagicAndre1981** [comment]
yeah, it [is totally EF5](https://www.nuget.org/packages/EntityFramework.Firebird/)

> 
> **Dependencies**
> 
>         EntityFramework (>= 6.0.0) 

![grafik](https://cloud.githubusercontent.com/assets/8274816/26511901/45a87026-4264-11e7-99b5-1d1803027446.png)

![grafik](https://cloud.githubusercontent.com/assets/8274816/26511938/7345c01a-4264-11e7-8140-0d7e10105712.png)

**Comment by MagicAndre1981** [comment]
2 weeks later, still no response. 

In `internal class ProviderServicesFactory` you have a method `private static DbProviderServices GetInstance(Type providerType)` which tries to get a public static Property with name `Instance`
```

const BindingFlags bindingFlags = BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic;

            var instanceMember = providerType.GetStaticProperty("Instance")
                                 ?? (MemberInfo)providerType.GetField("Instance", bindingFlags);
            if (instanceMember == null)
            {
                throw new InvalidOperationException(Strings.EF6Providers_InstanceMissing(providerType.AssemblyQualifiedName));
            }

```

If this fails it raises an InvalidOperationException with the error EF6Providers_InstanceMissing which is defined as 

> <value>The Entity Framework provider type '{0}' did not have a static property or field named 'Instance'. Entity Framework providers must declare a static property or field named 'Instance' that returns the Singleton instance of the provider.</value>

yeah, so your wrap provider misses this Instance property, which is required for EF6 providers, but yeah, this is because I use EF5 

Because you also don't have any Eventsource logging added, you can't really see what your code does. I've removed the EFCache package now, build my own Cache for the whole application (not only EF) based on [MemoryCache Class](https://msdn.microsoft.com/en-us/library/system.runtime.caching.memorycache.aspx) and added proper Eventsource logging support and here I see statistics about the Cache hit/miss ratios and see that it actually works. 

Bye, bye and an advice to all other users, NEVER use any peace of code of him, it is a waste of time.
