### ISSUE TITLE
SqlCacheDependency

### ISSUE THREAD

**Issue by ardalis** [moozzyk/EFCache#13]
I'm looking for something like what you have that uses a SqlCacheDependency to automatically expire the cache if the underlying table is updated. Have you experimented with that at all?

**Comment by moozzyk** [comment]
I have not but looking at it now I am not sure if it is a good fit. It seems it requires attaching a subscription to a command and it requires the connection to the database to be open all the time. EF opens the connection only to execute query/command and closes it immediately when it's done. There is also a [long list](https://msdn.microsoft.com/library/ms181122.aspx) of limitations and I think queries EF generate can easily violate at least some of them. Possibly it could be done outside EF by creating a number of `SELECT Col1, Col2...` queries and keeping a separate connection that is opened all the time but I think this can be done even now without changes to EF Cache. Finally, SqlCacheDependency is a SQL concept while EFCache should work regardless of the database you use.

**Comment by ardalis** [comment]
Thanks. The table-based version isn't restrictive of which kinds of queries can be made, but does require a persistent connection from the application to perform polling and check if the table has changed. Still the ability to have instant notifications whenever the underlying data source changes is extremely compelling, and unfortunately it's been difficult to implement with any version of EF to date. I keep hoping, though.

**Comment by moozzyk** [comment]
I thought the table-based wouldn't require polling - you would be notified about changes for the given table (i.e. you create SqlCacheDependency on `SELECT Col1, Col2... FROM tblA` and you are notified about changes happening to this table). You could generate these quereies/commands automatically when starting based on S-Space model. If you get notified about a change you could just invalidate the cache using [`InvalidateSets`](https://github.com/moozzyk/EFCache/blob/master/EFCache/ICache.cs#L37)

**Comment by ardalis** [comment]
Probably we're referring to different things, but table-based to me is using triggers that require db setup on a per-table basis. This approach requires app polling but has no query limitations. The other one, which works on SQL SERVER 2005 and later (which used to be cutting edge back in the day) uses indexed views and has the same limitations as that technology/feature (no SELECT *, etc.). It sends notifications to apps that register/subscribe for updates.

**Comment by moozzyk** [comment]
Yeah. I was referring to SqlCacheDependency (which AFAICT is not supported on Azure or in the new .NET Core SqlClient).
