### ISSUE TITLE
How to access cache instance in DbConfiguration from DbContext?

### ISSUE THREAD

**Issue by UweKeim** [moozzyk/EFCache#14]
Trying to delete all items from the cache, I've read [this discussion](https://efcache.codeplex.com/discussions/571007).

Ideally, I want to create a method `ClearCache()` in my `DbContext`-derived class which in turn accesses the `InMemoryCache` instance inside my `DbConfiguration`-derived class.

What I'm struggling with is:

How to get a reference to my `DbConfiguration`-derived class from within my `DbContext`-derived class?

[I've also asked on SO](https://stackoverflow.com/q/44833064/107625) but maybe I'm on the completely wrong path?

**Comment by moozzyk** [comment]
Just store a reference to the cache in a static variable before you pass it to the `CacheTransactionHandler` ctor and then you should be able to it access from anywhere. The cache is effectively singleton so I don't think there is any problem with doing this.

**Comment by UweKeim** [comment]
Thanks a lot.
