### ISSUE TITLE
Problem using Spatial type (DbGeography) with EFCache

### ISSUE THREAD

**Issue by Buyukcaglar** [moozzyk/EFCache#15]
Hi,

I have been using EFCache quite long time for my projects without any issues, thanks for your clean and transparent implementation.

For our new project we have to use Spatial type on one of our entity, which caused the following problem;

System.Data.Entity.Core.ProviderIncompatibleException: Spatial readers can only be produced from readers of type SqlDataReader. A reader of type EFCache.CachingReader was provided.

We would like to be able cache this entity also, is there any way to accomplish without excluding this entity from EFCache's caching mechanism?

Thanks in advance,

Onur

**Comment by moozzyk** [comment]
Unfortunately this is external to EFCache - fixing this requires breaking changes to EF provider model. You can find more details [here](https://efcache.codeplex.com/workitem/6) and [here]( https://efcache.codeplex.com/discussions/546912).
