### ISSUE TITLE
Implement ICloneable in CachingCommand

### ISSUE THREAD

**Issue by nphmuller** [moozzyk/EFCache#16]
EntityFramework expects a DbCommand implementation to implement ICloneable. I expect CachingCommand works in its current state because the database call is cancelled and the result is retrieved from the cache instead. Not implementing ICloneable gives problems however if EFCache is used in combination with other interceptors. 

See OdbcCommand, OleDbCOmmand and SqlCOmmand. All of which implement ICloneable.

For example, I tried to use [MiniProfiler](https://github.com/MiniProfiler/dotnet) together with EFCache. MiniProfiler's ProfiledDbCommand implements (and has to implement) ICloneable, which throws because it tries to called CachingCommand Clone() method, which doesn't exist.

I also created an issue at MiniProfiler. See https://github.com/MiniProfiler/dotnet/issues/175#issuecomment-298312062 and later

Do you see any problems with implementing ICloneable in EFCache?

**Comment by moozzyk** [comment]
I will look into this in the coming days.

**Comment by nphmuller** [comment]
Thanks for the quick implementation. 

Are you planning to release this any time soon? Or would I be better of compiling the latest version myself and releasing it to my private package feed?

**Comment by moozzyk** [comment]
@nphmuller - I am planning to release within 2 weeks (I want to add one more thing in the next version).

**Comment by nphmuller** [comment]
Great. Thanks!

**Comment by moozzyk** [comment]
@nphmuller - I pushed 1.1.1 to NuGet.
