### ISSUE TITLE
EF Core?

### ISSUE THREAD

**Issue by emilmuller** [moozzyk/EFCache#17]
Hi. Sorry for opening an issue on this. Didn't know how else to ask a question. Was wondering if you are planning to implement this for EF Core? I was thinking of maybe giving it a go, but was wondering if you knew if things are radically different there? I really love this library and wouldn't leave EF6 for Core until I knew I had a viable option :)

Kind regards, Emil

**Comment by moozzyk** [comment]
EF Core has a completely different architecture and I think almost none of this code would be useful/applicable. At this point I am not planning on creating a similar library for the EF Core. I suggest asking directly in the [EF Core](https://github.com/aspnet/EntityFramework) repo if 2nd level cache is a planned feature and if it isn't what is the recommend way to approach this.
