### ISSUE TITLE
How to clear cache?

### ISSUE THREAD

**Issue by somjetsomjet** [moozzyk/EFCache#22]
How to clear cache?

Please give some example.

thank

**Comment by moozzyk** [comment]
If you are using MemoryCache as the store you can use [Purge](https://github.com/moozzyk/EFCache/blob/a35a618eaf6bd2cf8580ed8617860d246ceb6399/EFCache/InMemoryCache.cs#L136) like in this test:
https://github.com/moozzyk/EFCache/blob/a35a618eaf6bd2cf8580ed8617860d246ceb6399/EFCacheTests/InMemoryCacheTests.cs#L100-L116
