### ISSUE TITLE
How to set cache expire?

### ISSUE THREAD

**Issue by somjetsomjet** [moozzyk/EFCache#23]
How to set cache expire?

please give some example.

thank

**Comment by moozzyk** [comment]
You can customize cache expiration by creating a custom caching policy derived from the `CachingPolicy` class and overriding the https://github.com/moozzyk/EFCache/blob/06d0356d5329405ad65fcdb2af89ed77a47a9eaf/EFCache/CachingPolicy.cs#L85
method to return sliding and absolute expiration values.

**Comment by object71** [comment]
@moozzyk This is not possible if the nuget package is used as the method is set as protected internal. I will download it now but consider changing that in the future

**Comment by moozzyk** [comment]
The method is `protected` so it is possible. You need to derive from the `CachingPolicy` class and override the method. Then pass the instance of your derived class to the `CachingProviderServices` constructor when registering the cache (or pass your custom caching policy as the second parameter to the [EntityFrameworkCache.Initialize](https://github.com/moozzyk/EFCache/blob/aa9d45d32eb2719cb92769a6d368226ee56bf2b4/EFCache/EntityFrameworkCache.cs#L13) method).
