### ISSUE TITLE
All context request have been cached not the methods use Cached() Extension

### ISSUE THREAD

**Issue by skhlil89** [moozzyk/EFCache#3]
Hi 
I have a problem with this useful library that is all entities and queries have been cached and some data are out of my control. I want to configure just every query that has Cached() extension insert into cache.

my configuration is here:

```
 public static class MemoryCacheResolver
    {
        public static readonly InMemoryCache Cache = new InMemoryCache();
    }

 public class ModuleConfiguration : DbConfiguration
    {
        public ModuleConfiguration()
        {
            var transactionHandler = new CacheTransactionHandler(SobhStore.Data.MemoryCacheResolver.Cache);

            AddInterceptor(transactionHandler);


            var cachingPolicy = new CachingPolicy();

            Loaded +=
              (sender, args) => args.ReplaceService<DbProviderServices>(
                (s, _) => new CachingProviderServices(s, transactionHandler,
                  cachingPolicy));
        }
    }
```

and the webconfig:
```

<entityFramework  codeConfigurationType="NiNiSet.Data.AllModuleConfiguration, NiNiSet">
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="v11.0" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    </providers>
  </entityFramework>

```

I really appreciate any help you can provide.

**Comment by moozzyk** [comment]
The default caching policy is to [cache results for all queries](https://github.com/moozzyk/EFCache/blob/master/EFCache/CachingPolicy.cs#L26-L30). The best way to control what should be cached is to create your own policy by subclassing the default `CachingPolicy` and overriding the `CanBeCached` method. 

`Cached()`\`NotCached()` extension methods are meant for one-off cases and not for controlling caching as whole.

**Comment by moozzyk** [comment]
Yesterday I updated the default caching policy to enable passing table names whose results should be cached. This will make it much easier to control what gets cached because you no longer need to derive from the caching policy. Note that if multiple tables are involved caching for all of them needs to be enabled to cache query results.
