### ISSUE TITLE
EFCache Clear All Items method

### ISSUE THREAD

**Issue by sefacan** [moozzyk/EFCache#34]
Hi,
I use nopCommerce with EFCache. But i can't clear all items with a method. 
I need registrable ICache object for Dependency Injection and Clear methods.

**Comment by moozzyk** [comment]
I have not used nopCommerce so I don't quite understand the challenge here and how it can be solved in/by EFCache.

**Comment by icnocop** [comment]
You should be able to call the `Purge` method to clear the cache on the `InMemoryCache` instance.
