### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by SHAliakbari** [moozzyk/EFCache#36]
Hi , 

I using this library to cache some base data information which does not changes frequently.
My database size is about 500GB but all of my base data s are about only 100MB.
Now my iis process grows to 50GB of memory usage !!! 
I only set caching for 10 table in CachingPolicy ! it leads my process to OutOfMemoryException and everything resets !

I think problem is on CommandTreeFacts . When it dispose ?!

**Comment by SHAliakbari** [comment]
I think problem is on CommandTreeFacts . When it dispose ?!

**Comment by moozzyk** [comment]
[Assuming the memory pressure is created by excessive caching]
EF Cache uses the SQL queries as keys. In general even for a small database it is possible to generate a lot of different queries and they all will be cached. Oftentimes the results of such queries are used only once and they are not worth caching. Check if you are not running in this situation. If this is the case you can override the `CanBeCached` method:

https://github.com/moozzyk/EFCache/blob/d5506af2264ceb2122e130eb10ad1858fa24bef1/EFCache/CachingPolicy.cs#L52

inspect SQL and reject caching. 

You could also try purging the cache by using the Purge method of InMemoryCache. It will remove stale items from the cache (Note - if you don't use expiration and you want to remove items you have to pass `true` to remove unexpired items when calling `Purge`: https://github.com/moozzyk/EFCache/blob/d5506af2264ceb2122e130eb10ad1858fa24bef1/EFCache/InMemoryCache.cs#L141).

The InMemoryCache is a very simple, dictionary based implementation. It evicts items only lazily and does not have built-in limits. If it is not good enough for you needs you can implement your own cache implementation by implementing the `ICache` interface or adapt one of the existing caches that offer more features.

**Comment by SHAliakbari** [comment]
Hi again,

i found what problem is .
when a sqlcommand creates with CachingCommandDefinition , sometimes does not fire dispose on DbContext dispose method. 
so command with  all resources remains in memory.
i found this by dumping memory and check it with windbg .
some of my commands has a commandtext with about 90Kb and this commandtext fires about 10 times in second . 
@moozzyk  do you have any idea ?

**Comment by SHAliakbari** [comment]
@moozzyk I finally end up with this :
` _command.Connection.Disposed += (sender,e)=>
                {
                    if(_command != null)
                    {
                        this.Dispose();
                    }
                };
` on ExecuteDbDataReader and ExecuteDbDataReaderAsync.

what do you think ?

**Comment by moozzyk** [comment]
I am not sure. I don't fully understand this leak. Can you create a repro project so that I can take a look? Also, can you post what `!GCRoot` returned for the leaked object?

**Comment by moozzyk** [comment]
OK. I don't think there is anything actionable on my side at this point.
