### ISSUE TITLE
Using with structure map and unit of work pattern

### ISSUE THREAD

**Issue by skhlil89** [moozzyk/EFCache#4]
Hi 
Maybe some thing wrong with this library beside using ioc? (with Structure map and unit of work pattern to access the db)

I also using this methods with multiple db context in my project.

**Comment by moozzyk** [comment]
I don't understand what you are asking. EF Cache works at the provider level. You register it once and globally and you don't see it in your app anymore (unless you want to cache specific queries). 

For multiple contexts see the discussion here: https://efcache.codeplex.com/discussions/657132 with linked threads. In general I think it's not a good idea to cache everything and if table names don't overlap I think things should work.
