### ISSUE TITLE
New release for EF6.3 does not support net461 or earlier

### ISSUE THREAD

**Issue by CZEMacLeod** [moozzyk/EFCache#40]
Since EF 6.3.0 supports net40, net45 as well as netstandard2.1 and the previous version of EFCache supported net40 and net45 is there a reason the current release does not target the same? 
Can we get net461 as the minimum version if it can be done instead of net462?
At the moment I am using 
```
    <PackageReference Include="EntityFramework.Cache" Version="1.1.3" Condition="'$(TargetFramework)'=='net461'" />
    <PackageReference Include="EntityFramework.Cache" Version="1.2.0" Condition="'$(TargetFramework)'!='net461'" />
```
as a work-around, but this is messy and may lead to more issues in the future.

**Comment by moozzyk** [comment]
It should be net46. The reason for not supporting version below net46 is that I took a change that depends [on change in the behavior introduced in .NET Framework 4.6](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?redirectedfrom=MSDN&view=netframework-4.8#culture-and-task-based-asynchronous-operations). I will look into enabling .NET Framework 4.6.

**Comment by moozzyk** [comment]
FYI - I pushed version 1.2.1 which targets net46 instead of net462 to NuGet.
