### ISSUE TITLE
Published version of EFCache 1.3.0 has lost its PublicKeyToken

### ISSUE THREAD

**Issue by CZEMacLeod** [moozzyk/EFCache#48]
The V1.3.0 package on NuGet.org contains dll files which are not StrongNamed and have 'lost' their PublicKeyToken:
`EFCache, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null`
The V1.2.1 package (and previous) contain dlls which are StrongNamed and have the PublicKeyToken 46c4868af4307d2c
`EFCache, Version=1.2.1.0, Culture=neutral, PublicKeyToken=46c4868af4307d2c`
I can't see anything in the commit history - other than perhaps moving to using VSCode?
Has the build/release process changed and/or the keyfile not been moved over?

**Comment by moozzyk** [comment]
Thanks for reporting! I will investigate and release a new strong named version. I guess some env variables were not set correctly when building the package.

**Comment by moozzyk** [comment]
I pushed version 1.3.1 to NuGet. Thanks for reporting!
