### ISSUE TITLE
Excluding query from caching

### ISSUE THREAD

**Issue by kraemeratsur** [moozzyk/EFCache#5]
Hello,

I want to exclude specific queries from beeing cached. For example, I don't want to cache data, that
is beeing fetch on demand via IQueryable through a grid-scroll-mechanism in the frontend. first problem, the amount of putted items (keys) is huge and blows up the cache. the amount of data (result) is huge as well and blows up the memory. furthermore the cached data is useless, because the grid always creates different keys (where-clause) depending on its scrollposition. What is the best practice to handle cases like that? How can I let the cache know, that a query shouldn't be cached? Anaylsing the key (sql) isn't a proper solution, because there are sql-statements with only small differences in the where-clause that decide over beeing or not beeing cached. This would be very hard to analyse and maintain. Maybe it is possible to identify queries over unique ids or something similar?! The best/easiest thing, I could imaging at the moment, is, setting a "cache"- or "nocache"-flag, when opening a new query and the cache could evalute the flag and ignore queries with flag "nocache". But I don't know, if something like this is possible. 

Thanks and regards

**Comment by moozzyk** [comment]
I agree that caching results for all queries is not a good idea. There are two ways of controlling what's getting cached:
- caching policy
- query blacklisting/whitelisting

Caching policy allows you to define what's getting cached based on the tables in the database the query is touching. You need to subclass the `CachingPolicy` class and override the [`CanBeCached`](https://github.com/moozzyk/EFCache/blob/master/EFCache/CachingPolicy.cs#L52-L53) method. I simplified this a little bit recently but adding a [ctor](https://github.com/moozzyk/EFCache/blob/master/EFCache/CachingPolicy.cs#L33) that takes names of the tables for which results should be cached but this version is not on NuGet yet.

If you want to enable caching based on a query you could create a no-caching caching policy (i.e. a policy where `CanBeCached` method returns always `false`) and then use the `.Cached` extension method on the query. I would recommend using the `.Cached` extension method however only for  one off cases and not as a caching strategy.
