### ISSUE TITLE
Serialization through the binary formatter fails in dotnet core

### ISSUE THREAD

**Issue by sergevm** [moozzyk/EFCache#50]
I'm in the process of migrating a full .net framework solution to .net core. We use the EFCache.Redis nuget package to set up 2nd level caching on EF. The version of EF we use is 6.4.4, we don't migrate to EF Core yet because of an incompatible existing database schema. 

I run into issues, and it looks like that the main reason may be that System.RuntimeType is not serializable in dotnet core by design, while it is in the .net full framework. I found an issue in the dotnet runtime repo [here](https://github.com/dotnet/runtime/issues/23169) which points in this direction, and a confirmation of this statement by the development team. 

The solution suggested there is that the fully qualified name of the type is used instead of the serialization of the RuntimeType. Just wanted to log the issue here, still have to dig into the code to see if I can help to resolve the issue :-)

**Comment by sergevm** [comment]
PR created https://github.com/moozzyk/EFCache/pull/51/commits/0c46523c1bb60efeb8a3a5a72b9bf8040337a2e8

**Comment by moozzyk** [comment]
Closed via b82ebf700053397ceca528b3a24235f56d42b177
