### ISSUE TITLE
Working with AsNoTracking()

### ISSUE THREAD

**Issue by Bykiev** [moozzyk/EFCache#53]
Hi, I'm new to this library and have some questions about using AsNoTracking(). 

1. Will be result cached if AsNoTracking() is used?
2. If so, will it be autoinvalidated when the value will be updated/removed/added?

Thank you!

**Comment by moozzyk** [comment]
It's been a while but AFAIR if you use `AsNoTracking()` the results will be cached. Cached results are invalidated when any transaction that touches a table they originated from is committed.

**Comment by Bykiev** [comment]
Thank you, do I understand your correctly, cache will be invalidated only when transaction was made by EF but not via other tools (like management studio)?

**Comment by Bykiev** [comment]
And one more question: will be results from cache attached tracked by DbContext? For ex:

```
var product = db.Products.First(); //here result is from cache
product.InStock = false;

await db.SaveChangesAsync(); // product should be updated
```

**Comment by moozzyk** [comment]
Yes - caching is implemented at the provider layer and upper layers are not even aware of it.
