### ISSUE TITLE
how to use it without DbConfiguration

### ISSUE THREAD

**Issue by qinshimignyue** [moozzyk/EFCache#8]
I use EF with IOC,I can not use DbConfiguration
 `   builder.RegisterType<PermissionEntities>().As<DbContext>().WithParameter(
    (p, c) => string.Equals(p.Name, "existingConnection"), (p, c) =>
    {
        return GetDbConnection();
    }).
     InstancePerRequest();`

**Comment by moozzyk** [comment]
I believe IoC and DbConfiguration are orthogonal. EF finds the configuration class independent on context creation. You just need to make sure it lives in the same assembly or point EF to find it as described on [msdn](https://msdn.microsoft.com/en-us/library/system.data.entity.dbconfiguration(v=vs.113).aspx).

**Comment by qinshimignyue** [comment]
http://images2015.cnblogs.com/blog/83201/201703/83201-20170329115626217-1069192425.png
DbConfiguration instance used before '“RedisCacheConfiguration' type was discovered

**Comment by qinshimignyue** [comment]
please tell me why??

 [DbConfigurationType(typeof(RedisCacheConfiguration))]
    public class PermissionEntities
         : DbContext, IRequest
    {

}

**Comment by qinshimignyue** [comment]
hello???

**Comment by moozzyk** [comment]
See: https://msdn.microsoft.com/en-us/data/jj680699. You seem to be using `DbModelBuilder` which is causing the issue. The documentation above explicitly calls this out and  says to use `DbConfiguration.SetConfiguration` static method at application startup (I believe it should be enough to  do this **before** you start using `DbModelBuilder`)

**Comment by qinshimignyue** [comment]
I didn't use DbModelBuilder. I just use autofac (IOC)

**Comment by qinshimignyue** [comment]
http://images2015.cnblogs.com/blog/83201/201703/83201-20170329133005998-1170210300.png
http://images2015.cnblogs.com/blog/83201/201703/83201-20170329133041576-217284110.png

**Comment by moozzyk** [comment]
Are you using Migrations? Maybe this forces config to be used? I think multiple assemblies can also lead to this issue. Try calling the `DbConfiguration.SetConfiguration` as the first thing in your app. Or try using app.config/web.config.

**Comment by qinshimignyue** [comment]
// AutomaticMigrationsEnabled = false;
same error

**Comment by qinshimignyue** [comment]
thank you sir,I resolved it.reason : as you said 'some place called first '.

**Comment by qinshimignyue** [comment]
thank you sir, 'some place called first '
3 other question :
1.can Distributed System share the same Key?
2.when the application retart ,can the same query share last cached data?
3.does this framework cache every query?
